version: 0.2
phases:
  build:
    commands:
      - echo  Paackaging JAR File...
      - mvn clean package
  post_build:
    commands:
      - echo Build complete
artifacts:
  files:
    - target/jettyjavase-1.0-SNAPSHOT.jar
  discard-paths: yes
